// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps

A https://help.salesforce.com/s/articleView?id=sf.named_credentials_define.htm&type=5[{partner-company-short-name} named credential] is required to be configured for {partner-product-short-name} to be able to invoke AWS services.
The AWS Quick Start generated user's access key and secret can be retrieved using AWS IAM as described in the following steps:

* Login to your AWS account that has sufficient privileges for creating an access key for the service account (https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateAccessKey.html[reference]).
* Within the AWS Console, select Services / Identity Access Management (IAM).
* Within IAM, select *Users*.
* Select the user specified in the AWS CloudFormation template definition.
* Select the *Security Credentials* tab.
* Under the *Access Key* section, select Create access key.
  This will create a key and allow for copying or downloading the contents.
* The access key ID and secret access key will be used to configure a {partner-company-short-name} named credential.
