// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps

Configure a https://help.salesforce.com/s/articleView?id=sf.admin_virtual_care_create_a_named_credential.htm&type=5[{partner-company-short-name} Named Credential^] so that {partner-product-short-name} can invoke AWS services.

To use AWS Identity and Access Management (IAM) to retrieve the user's access key and secret that's generated by this Partner Solution, do the following steps:

. Log in to your AWS account. This account must have sufficient privileges to create an access key for the service account. For more information, refer to https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateAccessKey.html[CreateAccessKey^].
. In the AWS Management Console, choose *Services > Identity Access Management (IAM)*.
. Choose *Users*.
. Choose the user specified in the AWS CloudFormation template definition.
. Choose the *Security Credentials* tab.
. Under the *Access Key* section, choose *Create access key*. This action creates an access key and allows you to copy or download the contents.

The access key ID and secret access key is used to configure a {partner-company-short-name} Named Credential.
